# Generated by Django 3.1 on 2022-01-03 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Earning',
        ),
        migrations.RenameModel(
            old_name='Earnings',
            new_name='Expense',
        ),
        migrations.RenameModel(
            old_name='Investments',
            new_name='Investment',
        ),
    ]
