# Generated by Django 3.1 on 2022-01-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance', '0002_auto_20220103_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='date',
            field=models.DateField(default='2022-01-03'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2022-01-03'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateField(default='2022-01-03'),
        ),
    ]
